import { Svg } from 'ui-kit/svg';

export const Icons = {
  arrowDown: Svg(require('./chevron-down.svg')),
  arrowLeft: Svg(require('./arrow-left.svg')),
  calendar: Svg(require('./calendar.svg')),
  dashboard: Svg(require('./dashboard.svg')),
  employees: Svg(require('./employees.svg')),
  eye: Svg(require('./eye.svg')),
  eyeHide: Svg(require('./eye-hide.svg')),
  logout: Svg(require('./logout.svg')),
  logoOnboarding: Svg(require('./logo-onboarding.svg')),
  onboarding: Svg(require('./onboarding.svg')),
  profile: Svg(require('./profile.svg')),
  achievements: Svg(require('./achievements.svg')),
  onboardingActive: Svg(require('./onboarding-active.svg')),
  profileActive: Svg(require('./profile-active.svg')),
  achievementsActive: Svg(require('./achievements-active.svg')),
  scripts: Svg(require('./scripts.svg')),
  search: Svg(require('./search.svg')),
  settings: Svg(require('./settings.svg')),
  done: Svg(require('./done.svg')),
  continue: Svg(require('./continue.svg')),
  blocked: Svg(require('./blocked.svg')),
  greeting: Svg(require('./greeting.svg')),
  tasks: Svg(require('./tasks.svg')),
  logoManagement: Svg(require('./logo.svg')),
  menu: Svg(require('./menu.svg')),
  plus: Svg(require('./plus.svg')),
  uploadImage: Svg(require('./upload-image.svg')),
  moreSquare: Svg(require('./more-square.svg')),
  moreSquarePrimary: Svg(require('./more-square-primary.svg')),
  edit: Svg(require('./edit.svg')),
  delete: Svg(require('./delete.svg')),
  image: Svg(require('./image.svg')),
  password: Svg(require('./password.svg'))
};
